from __future__ import annotations

from typing import Protocol


class Callback(Protocol):
    order: int

    def on_train_start(self, state) -> None: ...
    def on_step_start(self, state) -> None: ...
    def on_step_end(self, state) -> None: ...
    def on_checkpoint(self, state) -> None: ...
    def on_evaluation(self, state, results) -> None: ...
    def on_train_end(self, state) -> None: ...
